repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
    -   id: debug-statements
    -   id: end-of-file-fixer
        exclude: |
          environment.yml
          codecov.yml
-   repo: https://github.com/asottile/reorder_python_imports
    rev: v2.6.0
    hooks:
    -   id: reorder-python-imports
-   repo: https://github.com/psf/black
    rev: 21.8b0
    hooks:
    -   id: black
-   repo: https://github.com/asottile/blacken-docs
    rev: v1.11.0
    hooks:
    -   id: blacken-docs
        additional_dependencies: [black]
-   repo: https://github.com/PyCQA/flake8
    rev: 3.9.2
    hooks:
    -   id: flake8
        args: # arguments to configure flake8
        # making flake8 compatible with Black
          - "--max-line-length=88"
        # ignore errors for Black compatability
        # E203: ignore whitespace around " : "
        # T000: ignore TODOs
        # T001: ignore print statements
        # W503: ignore linebreak before binary operator
          - "--ignore=E203,T000,T001,W503,"
        additional_dependencies: [
            flake8-alfred,
            flake8-bugbear,
            flake8-builtins,
            flake8-comprehensions,
            flake8-docstrings,
            flake8-eradicate,
            flake8-print,
            flake8-pytest-style,
            flake8-todo,
            flake8-unused-arguments,
            pep8-naming,
            pydocstyle,
            Pygments,
        ]
